//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.Entity.Core.EntityClient;
using System.Data.Entity.Core.Objects;
using System.Data.Entity.Core.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("WCFProjectModel", "FK__employee__PId__1273C1CD", "project", System.Data.Entity.Core.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(EmployeeService.project), "employee", System.Data.Entity.Core.Metadata.Edm.RelationshipMultiplicity.Many, typeof(EmployeeService.employee), true)]

#endregion

namespace EmployeeService
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class WCFProjectEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new WCFProjectEntities object using the connection string found in the 'WCFProjectEntities' section of the application configuration file.
        /// </summary>
        public WCFProjectEntities() : base("name=WCFProjectEntities", "WCFProjectEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new WCFProjectEntities object.
        /// </summary>
        public WCFProjectEntities(string connectionString) : base(connectionString, "WCFProjectEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new WCFProjectEntities object.
        /// </summary>
        public WCFProjectEntities(EntityConnection connection) : base(connection, "WCFProjectEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<employee> employees
        {
            get
            {
                if ((_employees == null))
                {
                    _employees = base.CreateObjectSet<employee>("employees");
                }
                return _employees;
            }
        }
        private ObjectSet<employee> _employees;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<project> projects
        {
            get
            {
                if ((_projects == null))
                {
                    _projects = base.CreateObjectSet<project>("projects");
                }
                return _projects;
            }
        }
        private ObjectSet<project> _projects;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the employees EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToemployees(employee employee)
        {
            base.AddObject("employees", employee);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the projects EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToprojects(project project)
        {
            base.AddObject("projects", project);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="WCFProjectModel", Name="employee")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class employee : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new employee object.
        /// </summary>
        /// <param name="empid">Initial value of the empid property.</param>
        public static employee Createemployee(global::System.Int32 empid)
        {
            employee employee = new employee();
            employee.empid = empid;
            return employee;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 empid
        {
            get
            {
                return _empid;
            }
            set
            {
                if (_empid != value)
                {
                    OnempidChanging(value);
                    ReportPropertyChanging("empid");
                    _empid = StructuralObject.SetValidValue(value, "empid");
                    ReportPropertyChanged("empid");
                    OnempidChanged();
                }
            }
        }
        private global::System.Int32 _empid;
        partial void OnempidChanging(global::System.Int32 value);
        partial void OnempidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String empname
        {
            get
            {
                return _empname;
            }
            set
            {
                OnempnameChanging(value);
                ReportPropertyChanging("empname");
                _empname = StructuralObject.SetValidValue(value, true, "empname");
                ReportPropertyChanged("empname");
                OnempnameChanged();
            }
        }
        private global::System.String _empname;
        partial void OnempnameChanging(global::System.String value);
        partial void OnempnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> empsalary
        {
            get
            {
                return _empsalary;
            }
            set
            {
                OnempsalaryChanging(value);
                ReportPropertyChanging("empsalary");
                _empsalary = StructuralObject.SetValidValue(value, "empsalary");
                ReportPropertyChanged("empsalary");
                OnempsalaryChanged();
            }
        }
        private Nullable<global::System.Decimal> _empsalary;
        partial void OnempsalaryChanging(Nullable<global::System.Decimal> value);
        partial void OnempsalaryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String empAddress
        {
            get
            {
                return _empAddress;
            }
            set
            {
                OnempAddressChanging(value);
                ReportPropertyChanging("empAddress");
                _empAddress = StructuralObject.SetValidValue(value, true, "empAddress");
                ReportPropertyChanged("empAddress");
                OnempAddressChanged();
            }
        }
        private global::System.String _empAddress;
        partial void OnempAddressChanging(global::System.String value);
        partial void OnempAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> PId
        {
            get
            {
                return _PId;
            }
            set
            {
                OnPIdChanging(value);
                ReportPropertyChanging("PId");
                _PId = StructuralObject.SetValidValue(value, "PId");
                ReportPropertyChanged("PId");
                OnPIdChanged();
            }
        }
        private Nullable<global::System.Int32> _PId;
        partial void OnPIdChanging(Nullable<global::System.Int32> value);
        partial void OnPIdChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("WCFProjectModel", "FK__employee__PId__1273C1CD", "project")]
        public project project
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<project>("WCFProjectModel.FK__employee__PId__1273C1CD", "project").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<project>("WCFProjectModel.FK__employee__PId__1273C1CD", "project").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<project> projectReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<project>("WCFProjectModel.FK__employee__PId__1273C1CD", "project");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<project>("WCFProjectModel.FK__employee__PId__1273C1CD", "project", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="WCFProjectModel", Name="project")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class project : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new project object.
        /// </summary>
        /// <param name="projId">Initial value of the projId property.</param>
        public static project Createproject(global::System.Int32 projId)
        {
            project project = new project();
            project.projId = projId;
            return project;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 projId
        {
            get
            {
                return _projId;
            }
            set
            {
                if (_projId != value)
                {
                    OnprojIdChanging(value);
                    ReportPropertyChanging("projId");
                    _projId = StructuralObject.SetValidValue(value, "projId");
                    ReportPropertyChanged("projId");
                    OnprojIdChanged();
                }
            }
        }
        private global::System.Int32 _projId;
        partial void OnprojIdChanging(global::System.Int32 value);
        partial void OnprojIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String projname
        {
            get
            {
                return _projname;
            }
            set
            {
                OnprojnameChanging(value);
                ReportPropertyChanging("projname");
                _projname = StructuralObject.SetValidValue(value, true, "projname");
                ReportPropertyChanged("projname");
                OnprojnameChanged();
            }
        }
        private global::System.String _projname;
        partial void OnprojnameChanging(global::System.String value);
        partial void OnprojnameChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("WCFProjectModel", "FK__employee__PId__1273C1CD", "employee")]
        public EntityCollection<employee> employees
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<employee>("WCFProjectModel.FK__employee__PId__1273C1CD", "employee");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<employee>("WCFProjectModel.FK__employee__PId__1273C1CD", "employee", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
